#!/usr/bin/env bash
# Bootstrap this repo on an Ubuntu VM and run Jupyter Notebook on :8888
# with password auth.
#
# Usage (from anywhere, after cloning):
#   sudo JUPYTER_PASSWORD='your-strong-password' ./scripts/setup_ubuntu.sh
#
# If JUPYTER_PASSWORD is unset, you will be prompted (input is hidden).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SERVICE_NAME="quant-jupyter"
JUPYTER_PORT="${JUPYTER_PORT:-8888}"

if [[ "$(uname -s)" != "Linux" ]]; then
  echo "This script is for Ubuntu Linux VMs." >&2
  exit 1
fi

if [[ -f /etc/os-release ]]; then
  # shellcheck disable=SC1091
  . /etc/os-release
  if [[ "${ID:-}" != "ubuntu" && "${ID_LIKE:-}" != *"ubuntu"* && "${ID_LIKE:-}" != *"debian"* ]]; then
    echo "Warning: expected Ubuntu; continuing on ${PRETTY_NAME:-unknown}." >&2
  fi
fi

if [[ "${EUID}" -ne 0 ]]; then
  echo "Re-running with sudo..."
  exec sudo --preserve-env=JUPYTER_PASSWORD,JUPYTER_PORT,DEBIAN_FRONTEND "$0" "$@"
fi

TARGET_USER="${SUDO_USER:-${USER}}"
if [[ "${TARGET_USER}" == "root" ]]; then
  echo "Run this script with sudo from a normal user account, not as root." >&2
  exit 1
fi
TARGET_HOME="$(getent passwd "${TARGET_USER}" | cut -d: -f6)"
VENV_DIR="${PROJECT_ROOT}/.venv"
JUPYTER_DIR="${TARGET_HOME}/.jupyter"
CONFIG_PATH="${JUPYTER_DIR}/jupyter_server_config.py"
DEPLOY_ENV="${PROJECT_ROOT}/.deploy.env"

export DEBIAN_FRONTEND=noninteractive

echo "==> Installing system packages"
apt-get update -y
apt-get install -y --no-install-recommends \
  ca-certificates \
  curl \
  git \
  build-essential \
  software-properties-common \
  python3 \
  python3-venv \
  python3-pip \
  python3-dev \
  libffi-dev \
  libssl-dev

PYTHON_BIN="$(command -v python3)"
PY_MINOR="$("${PYTHON_BIN}" -c 'import sys; print(sys.version_info.minor)')"
PY_MAJOR="$("${PYTHON_BIN}" -c 'import sys; print(sys.version_info.major)')"
if [[ "${PY_MAJOR}" -lt 3 || "${PY_MINOR}" -lt 11 ]]; then
  echo "==> System Python is ${PY_MAJOR}.${PY_MINOR}; installing Python 3.12"
  add-apt-repository -y ppa:deadsnakes/ppa
  apt-get update -y
  apt-get install -y python3.12 python3.12-venv python3.12-dev
  PYTHON_BIN="$(command -v python3.12)"
fi

echo "==> Using ${PYTHON_BIN} ($("${PYTHON_BIN}" --version))"

if [[ -z "${JUPYTER_PASSWORD:-}" ]]; then
  echo
  read -r -s -p "Jupyter password: " JUPYTER_PASSWORD
  echo
  read -r -s -p "Confirm Jupyter password: " JUPYTER_PASSWORD_CONFIRM
  echo
  if [[ "${JUPYTER_PASSWORD}" != "${JUPYTER_PASSWORD_CONFIRM}" ]]; then
    echo "Passwords do not match." >&2
    exit 1
  fi
fi
if [[ -z "${JUPYTER_PASSWORD}" ]]; then
  echo "Jupyter password cannot be empty." >&2
  exit 1
fi

echo "==> Creating virtualenv at ${VENV_DIR}"
if [[ ! -x "${VENV_DIR}/bin/python" ]]; then
  "${PYTHON_BIN}" -m venv "${VENV_DIR}"
fi
chown -R "${TARGET_USER}:${TARGET_USER}" "${VENV_DIR}"

run_as_user() {
  sudo -u "${TARGET_USER}" -H env \
    PATH="${VENV_DIR}/bin:${PATH}" \
    VIRTUAL_ENV="${VENV_DIR}" \
    "$@"
}

echo "==> Installing Python dependencies"
run_as_user "${VENV_DIR}/bin/pip" install --upgrade pip setuptools wheel
REQ_FILTERED="$(mktemp)"
trap 'rm -f "${REQ_FILTERED}"' EXIT
grep -v -E '^(appnope([=<>~!]|$)|#|$)' "${PROJECT_ROOT}/requirements.txt" > "${REQ_FILTERED}"
run_as_user "${VENV_DIR}/bin/pip" install -r "${REQ_FILTERED}"
run_as_user "${VENV_DIR}/bin/pip" install -e "${PROJECT_ROOT}"

echo "==> Writing Jupyter config (password hashed; plaintext not stored)"
install -d -o "${TARGET_USER}" -g "${TARGET_USER}" -m 700 "${JUPYTER_DIR}"
HASH="$(JUPYTER_PASSWORD="${JUPYTER_PASSWORD}" "${VENV_DIR}/bin/python" -c \
  'import os; from jupyter_server.auth.security import passwd; print(passwd(os.environ["JUPYTER_PASSWORD"]))')"

cat > "${CONFIG_PATH}" <<EOF
# Generated by scripts/setup_ubuntu.sh — do not commit.
c = get_config()  # noqa: F821

c.ServerApp.ip = "0.0.0.0"
c.ServerApp.port = ${JUPYTER_PORT}
c.ServerApp.open_browser = False
c.ServerApp.allow_remote_access = True
c.ServerApp.root_dir = r"${PROJECT_ROOT}"
c.ServerApp.token = ""
c.ServerApp.password = r"${HASH}"
c.PasswordIdentityProvider.hashed_password = r"${HASH}"
c.PasswordIdentityProvider.password_required = True
EOF
chown "${TARGET_USER}:${TARGET_USER}" "${CONFIG_PATH}"
chmod 600 "${CONFIG_PATH}"

cat > "${DEPLOY_ENV}" <<EOF
QUANT_DIR=${PROJECT_ROOT}
VENV_DIR=${VENV_DIR}
SERVICE_NAME=${SERVICE_NAME}
JUPYTER_PORT=${JUPYTER_PORT}
TARGET_USER=${TARGET_USER}
EOF
chown "${TARGET_USER}:${TARGET_USER}" "${DEPLOY_ENV}"

echo "==> Installing systemd service ${SERVICE_NAME}"
cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<EOF
[Unit]
Description=Quant Jupyter Notebook
After=network.target

[Service]
Type=simple
User=${TARGET_USER}
Group=${TARGET_USER}
WorkingDirectory=${PROJECT_ROOT}
Environment=PATH=${VENV_DIR}/bin:/usr/bin
Environment=VIRTUAL_ENV=${VENV_DIR}
Environment=QUANT_PROJECT_ROOT=${PROJECT_ROOT}
ExecStart=${VENV_DIR}/bin/jupyter notebook --config=${CONFIG_PATH} --no-browser
Restart=always
RestartSec=5
UMask=0022

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now "${SERVICE_NAME}.service"

if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "Status: active"; then
  echo "==> Opening TCP ${JUPYTER_PORT} in ufw"
  ufw allow "${JUPYTER_PORT}/tcp" comment "quant jupyter" || true
fi

echo
echo "Setup complete."
echo "  Jupyter:  http://<vm-ip>:${JUPYTER_PORT}"
echo "  Auth:     password you set (no token)"
echo "  Service:  sudo systemctl status ${SERVICE_NAME}"
echo "  Update:   ./scripts/update_and_restart.sh"
echo
systemctl --no-pager --full status "${SERVICE_NAME}" || true
